import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar2 from "@/_components/shared/Navbar/Navbar";
import Footer from "@/_components/shared/Footer/Footer/Footer";
import ChatBot from "@/_components/StudyDestinationComponents/Shared/Components/chatbot/ChatBot";
import Providers from "@/_components/QueryClientProvider/Providers";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar2 />
          <div className="pb-10">
            {children}
            <ChatBot />
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
